### ISSUE TITLE
Overwrite Data Message

### ISSUE THREAD

**Issue by Soccer128** [sysdl132/sysdl132.github.io#2] opened 2020-11-22 19:11 UTC
This is for your scratch tutorial on converting scratch to exe. Whenever I launch the exe, it keeps popping up with messages about overriding files in the temp folder. How do I make it so my project doesn't say that.

Can I get rid of the command that creates temp files or can I make it so it doesn't constantly replace the temp file

**Comment by sysdl132** [comment] 2020-12-19 03:07
Hey @Soccer128 !
I'm sorry because I'm busy these days.

This problem caused by my compiler configuration. I found out that my compiler had a config problem. (I wrote this document without testing on that day)

![image](https://user-images.githubusercontent.com/54708046/102679537-73bfc600-41eb-11eb-82b4-f82bff1dcabe.png)


I'll edit the guide soon.😀 https://github.com/sysdl132/sysdl132.github.io/commit/2822bd7e049a28f6782ceb371bd4f930b6c6dd53

**Comment by sysdl132** [comment] 2020-12-27 13:12
(If you want to add some advice next time, you can open a discussion or go to: https://sl132.flarum.cloud )

**Comment by sysdl132** [comment] 2021-03-29 12:08
@Soccer128

**Comment by sysdl132** [comment] 2024-12-21 14:31
-> WEBSITE REFRESHED - CLOSING ALL ISSUES <-

**Closed as completed by sysdl132** 2024-12-21 14:31 UTC
Labels: question
